# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a30fc596c0a3946e4dca01c7a5ddd4128ce20b0c253df5d0ea623054344f2eac1c24e587b0407dd5880203372f801ee0d2c1da20b6664810dfa2362810a83e7e

test:
  secret_key_base: e6485314e41f88514919ed2ace5157f33d14bea249807c220e3b6f218323812f41b109a7fda5eb5a9d60cc25a4113ba58b59351a12540fe44f37ae35b362d224

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
